version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306
    volumes:
#     - ../common/setup.sql:/docker-entrypoint-initdb.d/setup.sql
     - ./sql:/var/lib/mysql
    environment:
      MYSQL_USER: OpenData
      MYSQL_DATABASE: OpenData
      MYSQL_PASSWORD: OpenData
      MYSQL_ROOT_PASSWORD: sjallabajs
  adminer: # For sql administration
    links:
      - mysql
    image: adminer
    ports:
      - 3739:8080
  dotnet:
    build:
      context: ../../
      dockerfile: ./container/production/Dockerfile.dotnet
    environment:
      ASPNETCORE_URLS: "http://*:9000"
      ASPNETCORE_ENVIRONMENT: "Development"
    links:
      - mysql
    ports:
      - 9000:9000 # Only exposed for testing
  react:
    build:
      context: ../../
      dockerfile: ./container/volumemount-friendly/Dockerfile.react
    volumes:
      - ../../frontend/src:/srv/opendata-frontend/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    ports:
      - 3000:3000
    links:
      - react
      - dotnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
