const userConstants = {
  SET_USER_LOGIN_REQUEST: 'USER_SET_USER_LOGIN_REQUEST',
  SET_USER_LOGIN_SUCCESS: 'USER_SET_USER_LOGIN_SUCCESS',
  SET_USER_LOGIN_FAILURE: 'USER_SET_USER_LOGIN_FAILURE',
  SET_USER_REGISTRATION_REQUEST: 'USER_SET_USER_REGISTRATION_REQUEST',
  SET_USER_REGISTRATION_SUCCESS: 'USER_SET_USER_REGISTRATION_SUCCESS',
  SET_USER_REGISTRATION_FAILURE: 'USER_SET_USER_REGISTRATION_FAILURE',
  SET_USER_CLEAR: 'USER_SET_USER_CLEAR',
};

export {
  userConstants,
};
